"""Add document management fields

Revision ID: fb4aebebfbb8
Revises: 3e26a21e6be3
Create Date: 2025-10-09 15:40:27.950903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4aebebfbb8'
down_revision = '3e26a21e6be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parsed_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('processing_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('processing_status')
        batch_op.drop_column('parsed_data')
        batch_op.drop_column('ocr_text')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('stored_filename')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
